version: '3'
services:
  snapserver:
    image: mmmaxwwwell/snapserver:latest
    #build: .
    container_name: snapserver
    ports:
      - 1780:1780
      - 1704:1704
      - 1705:1705
    networks:
      - snapserver
    env_file:
      ./settings/common.conf
    volumes:
      - ./appdata/snapserver/librespot-fifo:/var/cache/snapcast/snapfifo
      - ./settings/snapserver.conf:/etc/snapserver.conf
networks:
  snapserver: